"""initial schema: notes and tasks

Why this file exists:
    The first versioned migration — it builds the entire Phase 1 schema
    from an empty database. It creates, in dependency order, the
    `task_status` enum type and the `notes` and `tasks` tables, with
    columns, types, and server defaults that match the ORM models exactly.
    `alembic upgrade head` runs `upgrade()`; `alembic downgrade base`
    reverses it via `downgrade()`.

    Hand-authored (rather than autogenerated) so it is explicit and
    reviewable, and so the enum is created with the robust, idempotent
    pattern below. Regenerating via autogenerate later yields the same
    schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-29
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Revision identifiers used by Alembic. This is the root migration, so
# there is no parent (down_revision is None).
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Declare the PostgreSQL enum ONCE, with create_type=False so that columns
# using it do NOT try to auto-create the type (which would raise "type
# already exists"). We create/drop the type explicitly and idempotently
# (checkfirst=True) in upgrade()/downgrade(). The labels are the human
# values stored by the model (TaskStatus values), not the member names.
task_status = postgresql.ENUM(
    "Pending",
    "In Progress",
    "Completed",
    name="task_status",
    create_type=False,
)


def upgrade() -> None:
    """Create the enum type, then the notes and tasks tables."""
    bind = op.get_bind()

    # 1) Create the enum type first — the tasks table depends on it.
    #    checkfirst=True makes this safe to run against a DB where it might
    #    already exist.
    task_status.create(bind, checkfirst=True)

    # 2) notes table.
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "is_pinned",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # Mirror index=True on the model's primary key.
    op.create_index("ix_notes_id", "notes", ["id"], unique=False)

    # 3) tasks table.
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            task_status,
            nullable=False,
            server_default="Pending",
        ),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_tasks_id", "tasks", ["id"], unique=False)


def downgrade() -> None:
    """Reverse the upgrade: drop tables (reverse dependency order), then
    the enum type. Dropping a table removes its indexes automatically."""
    op.drop_table("tasks")
    op.drop_table("notes")
    task_status.drop(op.get_bind(), checkfirst=True)
